### ISSUE TITLE
Navmesh mount

### ISSUE THREAD

**Issue by adiif1** [vis2k/uMMORPG2D#1]
**Versions (please complete the following information)**
 - Unity Version: 2018.2.20f1
 - uMMORPG2D Version: last
 - Are you using a fresh uMMORPG2D version without any modifications? Fresh copy
    If not, then please try to reproduce it in a fresh Version and come back here.

**Describe the bug**
It looks like navmesh is for the character, not for our horse.

**To Reproduce**
Steps to reproduce the behavior, please explain every single click that is needed:
Just call a mount and you can you can move around water title etc

**Expected behavior**
-**Screenshots/Video**
![navmesh2d](https://user-images.githubusercontent.com/6035636/52247030-8b884c80-28e8-11e9-8ae2-88dc9b64de17.png)

**System (please complete the following information):**
 - Operating System 8.1 and 10

**Additional context**

**Comment by miwarnec** [comment]
looking into this now.
one possible solution is to do what I do in ummorpg 3d: put the character sprite in a child object and then offset it while mounted

**Comment by miwarnec** [comment]
fixed in V1.58!
