### ISSUE TITLE
Plugins for android

### ISSUE THREAD

**Issue by KVinS** [vis2k/uMMORPG2D#11]
**Versions (please complete the following information)**
 - Unity Version: [e.g. 2019.4.23f1]
 - uMMORPG2D Version: last

**Describe the bug**
Plugin excluded is configured incorrectly for android build.

**To Reproduce**
Steps to reproduce the behavior, please explain every single click that is needed:
1. Open Unity Editor '...'
2. Build for Android'....'

**Additional context**
```
Found plugins with same names, Assets/uMMORPG/Plugins/libuv2k/libuv_binaries/windows/x86/libuv.dll and Assets/uMMORPG/Plugins/libuv2k/libuv_binaries/windows/x64/libuv.dll. Delete the one of the duplicate plugins.
UnityEditor.AndroidPluginImporterExtension:CheckFileCollisions (string)
UnityEditorInternal.PluginsHelper:CheckFileCollisions (UnityEditor.BuildTarget)
UnityEngine.GUIUtility:ProcessEvent (int,intptr)
```

```
Found plugins with same names, Assets/uMMORPG/Plugins/SQLite/sqlite_x86/sqlite3.dll and Assets/uMMORPG/Plugins/SQLite/sqlite_x64/sqlite3.dll. Delete the one of the duplicate plugins.
UnityEditor.AndroidPluginImporterExtension:CheckFileCollisions (string)
UnityEditorInternal.PluginsHelper:CheckFileCollisions (UnityEditor.BuildTarget)
UnityEngine.GUIUtility:ProcessEvent (int,intptr)
```

**Comment by miwarnec** [comment]
libuv was removed.
checking sqlite3, probably some import setting.

**Comment by miwarnec** [comment]
regarding the sql error: make sure that the x64 plugin only has x64 platform selected and vice versa:
<img width="255" alt="2022-01-09_00-36-38@2x" src="https://user-images.githubusercontent.com/16416509/148652189-c50e2e30-f7a7-4c37-90fc-c8769b7d6d59.png">
<img width="253" alt="2022-01-09_00-36-31@2x" src="https://user-images.githubusercontent.com/16416509/148652191-ffa86841-61f1-409d-90e5-7d26329e5d7d.png">
that's the case by default.
if it still happens just delete the x86 one
