### ISSUE TITLE
Plugins for WebGL

### ISSUE THREAD

**Issue by KVinS** [vis2k/uMMORPG2D#12]
**Versions (please complete the following information)**
 - Unity Version: [e.g. 2019.4.23f1]
 - uMMORPG2D Version: last

**Describe the bug**
Plugin excluded is configured incorrectly for WebGL build.

**To Reproduce**
Steps to reproduce the behavior, please explain every single click that is needed:
1. Open Unity Editor '...'
2. Build for WebGL '....'

**Additional context**
```
Plugin 'libuv.dll' is used from several locations:
 Assets/uMMORPG/Plugins/libuv2k/libuv_binaries/windows/x64/libuv.dll would be copied to <PluginPath>/libuv.dll
 Assets/uMMORPG/Plugins/libuv2k/libuv_binaries/windows/x86/libuv.dll would be copied to <PluginPath>/libuv.dll
Please fix plugin settings and try again.

UnityEditor.Modules.DefaultPluginImporterExtension:CheckFileCollisions (string)
UnityEditorInternal.PluginsHelper:CheckFileCollisions (UnityEditor.BuildTarget)
UnityEngine.GUIUtility:ProcessEvent (int,intptr)
```

**Comment by miwarnec** [comment]
sorry, late reply.
libuv was removed :)

**Comment by KVinS** [comment]
It remains to solve the remaining 10 of my requests :D08.01.2022, 19:29, "vis2k" ***@***.***>:
sorry, late reply.
libuv was removed :)
