### ISSUE TITLE
NavMeshAgent2D sync error

### ISSUE THREAD

**Issue by KVinS** [vis2k/uMMORPG2D#13]
**Versions (please complete the following information)**
 - Unity Version: [e.g. 2019.4.23f1]
 - uMMORPG2D Version: 2.5

**Describe the bug**
Hello. I am getting weird sync error. I have moving NPCs and monsters. Some of them can stand in one place for a long time:
- The position of the entities is not synchronized until the moment it starts to move.
(For newly authorized players)

I was able to understand what the error was. Here is the order of events:

Entity start position: 0:0
The position of the entity on the server is 1:1

1. Client is authorized (Entity position 0:0)
2. NetworkNavMeshAgent2D.OnDeserialize (Entity position 1:1)
BUT
3. NavMeshAgent2D.agent.transform.position position is still 0:0
4. And when NavMeshAgent2D.Update occurs, the entity position is also returned to 0:0.

**Expected behavior**
`(Vector2.Distance (agent.agent.transform.position, position)> agent.speed * 2 && agent.isOnNavMesh))`
Is it possible to abandon this check altogether and do a warp right away if it initialState?
```
        if ((Vector2.Distance(transform.position, position) > agent.speed * 2 && agent.isOnNavMesh) 
            || initialState)
        {
            agent.Warp(position);
            //Debug.Log(name + " rubberbanding to " + position);
        }
```

**Screenshots/Video**
(server - left, client - right)
![2021-04-04_03-23-45](https://user-images.githubusercontent.com/3009807/113497593-3834d780-950e-11eb-8d74-f90a1595c891.png)

**Comment by KVinS** [comment]
Hi. I noticed another error.
After OnDeserialize, the moving character will usually teleport:
`agent.Warp (position);`
It seems that this metot reset the movement that is set above:
`agent.destination = destination;`
Therefore, I tried to swap these areas.
Now, characters start moving right after onDeserialize.

![2021-08-22_19-21-22](https://user-images.githubusercontent.com/3009807/130362518-3c9458cb-b88a-4539-b890-0bf793c10727.png)

**Comment by miwarnec** [comment]
> (Vector2.Distance (agent.agent.transform.position, position)> agent.speed * 2 && agent.isOnNavMesh))
Is it possible to abandon this check altogether and do a warp right away if it initialState?"

sorry for late reply. this was the reason for https://github.com/vis2k/uMMORPG2D/issues/4 as well.
fixed it on master. 
OnDeserialize now has 'if initialState then agent.Warp(position)' check!
thanks!



feel free to reopen if your issue or similar movement issues are still in V2.9 when it's out this week.

**Comment by KVinS** [comment]
Are you sure that there will be no problems with the movement of NPCs?10.01.2022, 14:56, "vis2k" ***@***.***>:

(Vector2.Distance (agent.agent.transform.position, position)> agent.speed * 2 && agent.isOnNavMesh))
Is it possible to abandon this check altogether and do a warp right away if it initialState?"

sorry for late reply. this was the reason for #4 as well.
fixed it on master.
OnDeserialize now has 'if initialState then agent.Warp(position)' check!
thanks!
