### ISSUE TITLE
Navigation 2d not working with polygon collider

### ISSUE THREAD

**Issue by iamallama** [vis2k/uMMORPG2D#15]
- Unity Version: Any
 - uMMORPG2D Version: Latest from gitlab repo
 - Are you using a fresh uMMORPG2D version without any modifications? Yes

**Describe the bug**
When using Super Tiled2Unity to import a map from Tiled, it creates a polygon collider with multiple paths. The AddPolygonCollider2Ds method doesn't support polygon colliders with multiple paths. There are no errors, but the method only gets the list of "Points" which is only the first path.
**To Reproduce**
Steps to reproduce the behavior, please explain every single click that is needed:
1. Open Unity Editor
2. Delete the existing maps
3. Import Super Tiled2Unity
4. Build a map with Tiled and save it in unity project. Be sure to include some colliders.
5. Drag the map prefab into the scene.
6. Bake the map and no walkable areas.

**Expected behavior**
Nav2d should handle polygons with multiple paths and should be able to bake them.

**System (please complete the following information):**
 - Operating System: Windows 10

**Additional context**
I know this is not necessarily related to uMMORPG, but Super Tiled2Unity is a common tool used to import maps from Tiled and Nav2d doesn't support the style of polygon collider it creates.

**Comment by miwarnec** [comment]
fixed, thanks so much
