### ISSUE TITLE
Party error

### ISSUE THREAD

**Issue by matheusoreis** [vis2k/uMMORPG2D#16]
**Versions (please complete the following information)**
 - Unity Version: 2019.4.8f1
 - uMMORPG2D Version: Last Build
 - I am using a UMMORPG without modifications

**Describe the bug**
IN: I was testing the server with some friends and when I joined the group I got the error, I went to investigate to be sure of the bug and I realized that when I was in a group and one of the group members was too far away and took damage from some mob "while being away from the others group members "the error appears, I tested it on a clean version of ummorpg and the error also occurs in the same way, that is, being in a group and very far from the others, when receiving damage from some mob the error happens.

PTBR: Estava testando o servidor com alguns amigos e ao entrar em grupo recebi o erro, fui investigar para ter certeza do bug e percebi que ao estar em grupo e um dos membros do grupo estar muito longe e levar dano de algum mob "estando longe dos demais membros do grupo" o erro aparece, testei em uma versão limpa da ummorpg e o erro também ocorre da mesma forma, ou seja estando em um grupo e muito longe dos demais, ao receber dano de algum mob o erro acontece.

**To Reproduce**
Steps to reproduce the behavior, please explain every single click that is needed:
1. Open Unity Editor '...'
2. Build for Windows '....'
3. I sent the client to friends
4. we joined in group
5. when taking damage being too far from the others
6. The error happens

**Screenshots/Video**
https://imgur.com/a/vDSaqwh

**System (please complete the following information):**
 - Windows 10 last build
 - 12gb Ram
 - 256gb ssd

**Comment by miwarnec** [comment]
![image](https://user-images.githubusercontent.com/16416509/125182725-09cc4400-e243-11eb-9cca-853292a61695.png)

**Comment by miwarnec** [comment]
@leahos sorry for late reply.
I just tried it and couldn't reproduce the error.
could you please make a video and then reopen this issue?

I believe you, but I need to know how to reproduce it. otherwise I can't fix it :)
