### ISSUE TITLE
Simple problem that occurs when you tried to use a skill based in TargetBuff

### ISSUE THREAD

**Issue by Ian03** [vis2k/uMMORPG2D#17]
**Desktop 
 - OS:Windows 10 64 BITS Build 21H1 build 19043
 - Browser microsoft edge
 - Version Remastered 2.7
- I didn't make any changes to the code base

**Describe the bug**
When you go to use skill, it just doesn't use it because it can't catch the target

**Screenshots**

![Bug](https://i.imgur.com/qg8y0XI.gif)

**Additional context**
the only solution I could come up with would be to use the method from the previous version, it seems to fix the problem.

search and open the class public class 

search for

    public static float ClosestDistance(Collider2D a, Collider2D b)
    {
        // 2D physics offer Collider2D.Distance(Collider2D)
        // which works for far-apart and overlapping!
        ColliderDistance2D distance2D = a.Distance(b);
        return distance2D.isOverlapped ? 0 : distance2D.distance;
    }

change to something like this

        //Classic Metod
        return Vector2.Distance(a.ClosestPointOnBounds(b.transform.position),
        b.ClosestPointOnBounds(a.transform.position));

**Comment by miwarnec** [comment]
checking..

**Comment by miwarnec** [comment]
great find. unlike 3D, 2D can't handle collider distance check to self.
this is now handled manually. fix is in next release.
