### ISSUE TITLE
Pet health is set to maxHealth calculated at level 1 on summon regardless of pet level

### ISSUE THREAD

**Issue by iamallama** [vis2k/uMMORPG2D#2]
**Versions (please complete the following information)**
 - Unity Version: 2018.3.8
 - uMMORPG2D Version: Most recent
 - Are you using a fresh uMMORPG2D version without any modifications? Yes

**Describe the bug**
When you summon a pet, their health is set to maxHealth which is dependent on the pet's level (linearInt). When a petItem is used an a pet is instantiated, their health is set before their level so maxHealth refers to the default level of 1. Meaning that on summon the pet's health is set to their base health at level 1 regardless of what level they are now.

**To Reproduce**
1. Open uMMORPG2d in unity.
2. Press play to start play mode.
3. Press Server & Play to login.
4. Select a character and join the world.
5. Select character GameObject in the editor and adjust their level to 5 (shortcut to having to level up).
6. Also set your gold to 1000 so you can buy the baby sapling.
7. Go to alchemist and buy the "baby sapling" pet.
8. Go into inventory and click pet item to summon it.
9. Click on pet game object in editor and adjust level to 5 (shortcut to having to level up)
10. Click on baby sapling item in inventory to summon it.
11. Health is set to 100, which is base health at level 1.
12. Let pet regenerate some health.
13. Unsummon pet.
14. Summon pet again.
15. Health is set back to 100 instead of where it was on unsummon.

**Expected behavior**
Health should be set to it's previous value on summon instead of the max 

**Screenshots/Video**
![Pet Health](https://user-images.githubusercontent.com/4924829/61082720-e6b1f400-a3de-11e9-9d49-f795cb98574b.gif)

**System (please complete the following information):**
N/A

**Additional context**
This is actually a pretty simple fix. In `[project]\Assets\uMMORPG\Scripts\ScriptableItems`, lines 27 and 28 (inside the `use` method where health and level is initially set), swap them so that level is set before health.

**Comment by miwarnec** [comment]
fix is in next version, thanks @iamallama
