### ISSUE TITLE
Entity desync after dying. 2d Remastered (didn't test other assets)

### ISSUE THREAD

**Issue by iamallama** [vis2k/uMMORPG2D#4]
- Unity Version: 2020.1.17, though this should be an issue with any version.
 - uMMORPG2D Version: Latest, cloned from the GitLab repo 5 minutes before the test.
 - Are you using a fresh uMMORPG2D version without any modifications? No, but modifications were removing unnecessary elements/objects from the scene to make reproduction easier. Detailed list of changes as follows:
```
- Deleted all saplings except for one.
- Removed Dungeon map and all layers except for the `Main World Terrain`
- Removed any other terrain/map game objects that weren't needed for demo.
- Rebaked map
- Sapling prefab
    - Increased `Move Distance` and `Follow distance` in Monster component to 20 to allow moving the monster away from spawn.
    - Decreased `Death Time` and `Spawn Time` to 5 so I don't have to wait too long for respawn.
- Warrior prefab
    - Increased `Speed` to 10 so it's easier to move around.
    - Turned on `Invulnerable` in combat component so I don't have to deal with dying.
- Disabled `Force Single Window` in project settings so I can demo two windows.
```
Screenshot of project to show changes to scene

![Screenshot of project to show changes to scene](https://user-images.githubusercontent.com/4924829/111035433-691e6280-83cf-11eb-9ce4-9796c9cee58d.png)

**Describe the bug**
Separate client and server required.
When you kill a monster and they respawn, on the client the monster shows at it's death location for several seconds before warping back to the initial spawn location. On the server they warp back immediately but not on the client. I assume the entity is disabled after death, but before respawn and any warp back to original spawn is silently ignored on the client, but works on the server. When the mob is respawned, the entity is enabled again and shows in the death location for several seconds before the rubber-banding kicks in and resets their position. This can be reproduced on local client/server builds as seen here:

![Demo](https://user-images.githubusercontent.com/4924829/111036185-df709400-83d2-11eb-83ee-3e30c5f1694b.gif)

**To Reproduce**
1. Make changes as described above (this is optional, but makes it easier to reproduce and eliminates variables.
2. Build for Windows
3. Run build, enter credentials and select `Server & Play` mode. Create/select a character and join the world. This will become our server that we connect another client to.
4. Run build again, enter different credentials and select `Login` mode. Create/select a character and join the world. This is our client that we will see the issue.
5. On the server window, move towards the monster so the original spawn point can be seen in the window, but not close enough to be attacked (the client will be performing the actions).
6. On the client window, move towards monster and "kite" them so they are away from their spawn point and can be seen on the server window.
7. Kill the monster with the client (this can be done by server also, it's more important that the monster dies away from it's spawn location).
8. Let monster disable (after loot time and before respawn time)
9. When monster respawns, client should show the monster at the death location while the server shows the monster back at it's spawn location.
10. After several seconds, the client syncs back up to server.

**Expected behavior**
Client/Server should always be in sync.

**Screenshots/Video**
See above

**System (please complete the following information):**
 - Win 10 with latest updates.

**Additional context**
This is an issue because during that several seconds of desync, the client can still interact with the monster. Initiating an attack and moving towards their location. It's frustrating to then have the monster warp away before you can attack like they were never there.

**Comment by miwarnec** [comment]
checking

**Comment by miwarnec** [comment]
can reproduce

**Comment by miwarnec** [comment]
NetworkNavMeshAgent2D.RpcWarp is called during respawn from Monster.OnDead -> RegularNavMeshMOvement->Warp.

at that time the monster has 0 observers though.
so the rpc isn't sent to anyone.

**Comment by miwarnec** [comment]
fixed.
NetNavMeshAgent2D.Deserialize now always warps to 'position' if spawning (= if initialstate)
